# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
  # Analizador  - NLU
  - name: HFTransformersNLP
    model_name: "bert"
    model_weights: "bert-base-multilingual-cased"
    cache_dir: null

  - name: LanguageModelTokenizer

  - name: LanguageModelFeaturizer

    # Clasificador
  - name: DIETClassifier
    # Hiperparámetros
    epochs: 100
    learning_rate: 0.001
    drop_rate: 0.2
    weight_sparsity: 0.8
    batch_size: [ 64, 256 ]
    embedding_dimension: 20
    entity_recognition: False

  - name: FallbackClassifier
    threshold: 0.7

policies:
  # Predictor  - DL
   - name: LSTMPolicy
     # Hiperparámetros
     max_history: 5
     epochs: 50
     batch_size: 32
     validation_split: 0.2
   - name: RulePolicy
     core_fallback_threshold: 0.4
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
