language: es

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    # Clasificador
  - name: SklearnIntentClassifier
    C: [ 1, 2, 5, 10, 20, 100 ]
    kernels: [ "linear" ]
    "gamma": [ 0.1 ]
    "max_cross_validation_folds": 5
    "scoring_function": "f1_weighted"

policies:
  # Predictor  - DL
  - name: LSTMPolicy
     # Hiperparámetros
    max_history: 5
    epochs: 50
    batch_size: 32
    validation_split: 0.2
  - name: RulePolicy